language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3.5"

env:
  - PYYAML_VERSION="3.12"
  - PYYAML_VERSION="4.1"

matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"

install: 
  - pip install pyyaml~=$PYYAML_VERSION
  - pip install --editable .
  - pip install pytest-cov coveralls

script: 
  - pip freeze
  - pytest --cov=oyaml

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
